services:

  db:
    image: mysql:8.4
    container_name: wallet_mysql_db
    networks:
      - api-common-net
    env_file: .env.test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_worker
    networks:
      - api-common-net
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.test
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


volumes:
  db_data:

networks:
  api-common-net:
    driver: bridge
