name: Build

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.12.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        make install
    - name: Run linters
      run: |
        make linter
    - name: upping project
      run: |
        make up
    - name: Test with pytest
      run: |
        make test
